### ISSUE TITLE
Error in convertAllYaml2RDataframesT20

### ISSUE THREAD

**Issue by adityabindal** [tvganesh/yorkr#2]
Recreate with `33602.yaml` and `33603.yaml` from IPL T20 data (attached).

`Error: All select() inputs must resolve to integer column positions.
The following do not:
*  batsman
*  bowler
*  nonStriker
*  byes
*  legbyes
*  noballs
*  wides
*  nonBoundary
*  penalty
*  runs
*  extras
*  totalRuns
*  wicketFielder
*  wicketKind
*  wicketPlayerOut`

R version 3.3.3 (2017-03-06)
[336002.txt](https://github.com/tvganesh/yorkr/files/908292/336002.txt)
[336003.txt](https://github.com/tvganesh/yorkr/files/908293/336003.txt)

**Comment by tvganesh** [comment]
Hi, I know the convertAllYaml2RDataframesT20() gives error for some Yaml files. I am not sure if the error is in the convert code or in the yaml frame itself. As I have mentioned in my post & book a couple of files gives this error. I ignore these files. Feel free to debug it, if you want. 

Regards
Ganesh

**Comment by adityabindal** [comment]
Thanks Ganesh. I've been investigating. The issue is in parseYamlOver() when the yaml delivery schema changes because of injuries. For instance in 336002.yaml:

       - 6.3:
            batsman: HH Gibbs
            bowler: V Kohli
            non_striker: AC Gilchrist
            replacements:
              role:
                - in: V Kohli
                  out: JH Kallis
                  reason: injury
                  role: bowler
            runs:
              batsman: 1
              extras: 0
              total: 1

And in 336003.yaml:

          batsman: SE Marsh
            bowler: Mohammad Hafeez
            non_striker: Yuvraj Singh
            replacements:
              role:
                - in: Yuvraj Singh
                  out: KC Sangakkara
                  reason: injury
                  role: batter
            runs:
              batsman: 1
              extras: 0
              total: 1

**Comment by adityabindal** [comment]
Fixed and tested. I created a pull request.

Thanks,
Aditya
